# Generated by Django 4.2.1 on 2023-05-25 12:37

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('sexual_identity', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('my_lat', models.CharField(blank=True, max_length=100, null=True)),
                ('my_long', models.CharField(blank=True, max_length=100, null=True)),
                ('min_distance_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('max_distance_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('gender_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('sexual_identity_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.DateField(blank=True, null=True)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
                ('dreams', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(blank=True, max_length=300, null=True)),
                ('report_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like2', to=settings.AUTH_USER_MODEL)),
                ('who_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=api.models.ProfileImage.nameFile)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_on', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to=settings.AUTH_USER_MODEL)),
                ('user_blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blocked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
